### ISSUE TITLE
ksmbd 3.5.4 fails to build on Linux 5.10.0: lockdep_assert_not_held is unavailable

### ISSUE THREAD

**Issue by G0o9leA1** [cifsd-team/ksmbd#628]
### Environment

- ksmbd version: 3.5.4
- Kernel version: Linux 5.10.0
- Architecture: arm32

### Expected behavior

The module should build successfully, because the README states that Linux kernel 5.4 or later is supported.

### Actual behavior

The build fails in `transport_ipc.c` because `lockdep_assert_not_held()` is not available in Linux 5.10.0:

```text
transport_ipc.c: In function 'ksmbd_rpc_write':
transport_ipc.c:838:2: error: implicit declaration of function 'lockdep_assert_not_held'
  lockdep_assert_not_held(&sess->rpc_lock);
  ^~~~~~~~~~~~~~~~~~~~~~~

make[2]: *** [scripts/Makefile.build:279: .../transport_ipc.o] Error 1
```

### Analysis

`lockdep_assert_not_held()` was added upstream after Linux 5.10. Therefore current ksmbd cannot compile against an unmodified 5.10 kernel without a compatibility guard, despite the documented “5.4 or later” support.

### Suggested direction

Please add a compatibility guard for kernels that do not provide `lockdep_assert_not_held()`

I can test a proposed patch on Linux 5.10.0.
